### ISSUE TITLE
Can i use input type file?

### ISSUE THREAD

**Issue by OneX** [ohlincik/craft-perform#2]
I have a lot of problems trying to make file input to work, so is there an example of how to use input type field?

**Comment by ohlincik** [comment]
Unfortunately, file input (a.k.a. file upload) is not currently supported. Can you elaborate on how you'd envision this to work?

How would be the uploaded files included in the Control Panel section? Just a link or embedded somehow? Would you be looking for the files to be sent as an attachment together with the submission notification?
