### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [ohlincik/craft-perform#4]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `perfectus\perform\elements\SubmissionQuery` located in `./vendor/perfectus/perform/src/elements/db/SubmissionQuery.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/elements/db/SubmissionQuery.php src/elements/SubmissionQuery.php
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by ohlincik** [comment]
Thanks, @brandonkelly for posting this. I've noticed this notice in the past and was getting ready to figure out how to fix it. Now you've just made it much easier. Much appreciated!

**Comment by ohlincik** [comment]
This has been now fixed in 3092f677ef081d35b6240d8b9022f8a8b6a2155c

**Comment by brandonkelly** [comment]
Thanks! Looks like the Plugin Store hasn’t picked up the update yet, and from my end it looks like that’s because we’ve lost connection with your GitHub repo. Can you please log into https://id.craftcms.com/ and reconnect your GitHub account?

**Comment by ohlincik** [comment]
@brandonkelly you were spot on diagnosing the issue. I've re-authorized GitHub in my Craft ID account. Hopefully, this will allow Plugin Store to pick up the update. Thanks for all your help with this. Much appreciated!

**Comment by brandonkelly** [comment]
Thanks! Just pulled in the new version, and recreated the plugin’s webhook to be sure that future versions get pulled in automatically. Have also verified that v1.0.2 isn’t getting any deprecation errors from Composer :)

**Comment by ohlincik** [comment]
Thank you @brandonkelly! Much appreciated. Keep up the amazing work with Craft CMS.
